---
title: "ADV Final Project"
author: "Darien Geyen, Austin Lee, Michael Mulvihill, Zach Stabrowski"
date: last-modified
subtitle: "ADV"
format: 
   html:
     toc: true
     toc-location: left
     df-print: paged
     embed-resources: true
---
## Imports

```{r}
## Libraries
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(sf))
suppressPackageStartupMessages(library(ggmap))
suppressPackageStartupMessages(library(leaflet))
suppressPackageStartupMessages(library(osrm))
suppressPackageStartupMessages(library(stringr))
```

## Exploring the Data

```{r}
## Read in CSVs
phone_calls <- read_csv("311_Phone_Call_Log_Mod.csv", show_col_types = F)
businesses <- read_csv("Business_Licenses.csv", show_col_types = F)
code_enforcement <- read_csv("code_enforcement.csv", show_col_types = F)
public_facilities <- read_csv("Public_Facilities.csv", show_col_types = F)
parks <- read_csv("Parks_Locations_and_Features.csv", show_col_types = F)
street_lights <- read_csv("Street_Lights.csv", show_col_types = F)
```

```{r}
## Read in shapefiles
school_boundaries <- 
  st_read("School_Boundaries/School_Boundaries.shp")

abandoned_properties <- 
  st_read("Abandoned_Property_Parcels/Abandoned_Property_Parcels.shp")

city_council_districts <- 
  st_read("City_Council_Districts/City_Council_Districts.shp")

census_2020 <- 
  st_read("2020_CensusData/2020_CensusData.shp")
```

```{r}
## Look at column names to see what we're working with
colnames(phone_calls)
colnames(businesses)
colnames(code_enforcement)
colnames(public_facilities)
colnames(parks)
colnames(street_lights)
```

```{r}
## Plot shapefiles
plot(school_boundaries$geometry)
plot(census_2020$geometry)
plot(city_council_districts$geometry)
plot(abandoned_properties$geometry)
```
## Constants
```{r}
meters_to_sq_miles <- 3.861e-7
meters_to_miles <- 1609.34
```
## Tab 1 - 
```{r}
## Call Date is a POSIXct, use that for the check in the server
str(phone_calls)

## Remove dirty entries
phone_calls <- phone_calls%>%filter(Called_About!="*No Article Found*")
```

## Tab 2 - 
```{r}
## Variables/logic for backend of tab 2 go here
```

## Tab 3 - 
```{r}
## Variables/logic for backend of tab 3 go here
```

## Tab 4 - School/Park Routes with Lights
```{r}
## Look at park types
table(parks$Park_Type)

## Get the "kid friendly" parks - no cemeteries or golf courses, etc.
kid_friendly_types <- c("Block Park", "Community Park", "Neighborhood Park")

## Decide whether or not a park is kid friendly
parks$Park_Type_Kid_Friendly <- parks$Park_Type %in% kid_friendly_types

## Look at lumens values
table(street_lights$Lumens)

## Clean lumens values so they are all numeric
street_lights <- street_lights %>%
  mutate(
    lumens_numeric = str_extract(Lumens, "\\d+[\\d,]*") %>% 
      str_replace_all(",", "") %>% 
      as.numeric()
  )

## Route buffer for either side of the osrm route in meters
route_buffer_meters <- 100

## Make parks and street lights spatial
parks_sf <- st_as_sf(parks, coords = c("Lon", "Lat"), crs = 4326)
street_lights_sf <- st_as_sf(street_lights, coords = c("Lon", "Lat"), crs = 4326)

## 3857 transformation for distance calculations
parks_3857 <- st_transform(parks_sf, 3857)
street_lights_3857 <- st_transform(street_lights_sf, 3857)
school_boundaries_3857 <- st_transform(school_boundaries, 3857)
```